# AutoGluon Predictor constructor arguments
# - see https://github.com/awslabs/autogluon/blob/ef3a5312dc2eaa0c6afde042d671860ac42cbafb/tabular/src/autogluon/tabular/predictor/predictor.py#L51-L159
#test_end_date: "2023-11-20"
ag_predictor_args:
  prediction_length: 90
  eval_metric: MAPE
  known_covariates_names: listing_price_mean,net_unit_price,promo_flag,holiday_flag,weekend_flag,holiday_ahead,promo_ahead
  target: "target"
  cache_predictions: False
  
# AutoGluon Predictor.fit arguments
# - see https://github.com/awslabs/autogluon/blob/ef3a5312dc2eaa0c6afde042d671860ac42cbafb/tabular/src/autogluon/tabular/predictor/predictor.py#L280-L651
ag_fit_args:
  random_seed: 12345
  hyperparameters:
   DeepAR:
     batch_size: 64
     num_batches_per_epoch: 22
     hidden_dim: 128
     max_epochs: 100 
     context_length: 120
     num_layers: 2
     hidden_size : 59
   # GBM:
   #   num_boost_round: 20
   # NN_TORCH:
   #   num_epochs: 2
  presets: "medium_quality"
  # num_bag_folds: 2
  # num_bag_sets: 1
  # num_stack_levels: 0

output_prediction_format: csv  # predictions output format: csv or parquet
feature_importance: true       # calculate and save feature importance if true
leaderboard: true              # save leaderboard output if true